### ISSUE TITLE
 cacheDir folder directory error

### ISSUE THREAD

**Issue by kangpou** [stantanasi/streamflix#147]
### Description

I noticed that the application created a folder named `cacheDir` in the system root directory, not in `/storage/emulated/0`. I haven't granted the app root permissions, so I'm not sure how it managed to do this.

### Provider

no

### Reproduction steps

no

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
It's weird because I use the cache folder to store the APK of the app when a new version is release, and I followed the tutorial from internet to do it.
[Code](https://github.com/stantanasi/streamflix/blob/f368269b2bf217af5fbd9dd191d6e1cef920081c/app/src/main/java/com/tanasi/streamflix/utils/InAppUpdater.kt#L50)

As of me, I just check on my phone and I don't see this folder. What devices are you using?
