### ISSUE TITLE
Non Android TV OS Devices

### ISSUE THREAD

**Issue by intellimediatv** [stantanasi/streamflix#99]
### Description

Non Android TV OS the newest 1.6.1 upon choosing a provider stays in mobile layout does not revert back to TV layout even after closing and reopening

### Reproduction steps

Choose provider i.e Sorastream

### App version

Version 1.6.1

### Operating system

HK1 Android TV Box on android 9.0

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
I created a special APK containing only the TV UI. You can locate it in the assets of [release 1.6.1](https://github.com/stantanasi/streamflix/releases/tag/v1.6.1), named **[streamflix-v1.6.2-tv.apk](https://github.com/stantanasi/streamflix/releases/download/v1.6.1/streamflix-v1.6.2-tv.apk)**. This is a temporary solution, but it allows you to have the new providers.
Even though it's version 1.6.2, I can't include it in Release 1.6.2 because the default app's in-app updater won't function properly.

**Comment by DjSpartaKe254** [comment]
![Screenshot_20240327-182540_Streamflix](https://github.com/stantanasi/streamflix/assets/105038308/c585da13-ba38-4de1-8030-911a6fd76d4d)
 Hello....i get this all the time, is is a known bug?

**Comment by Farid001979** [comment]
![Screenshot_2024-03-27-16-39-03-92_6bde43fb2a2a367f63867103e6a3e1f4.jpg](https://github.com/stantanasi/streamflix/assets/114618348/deed2ea3-95e1-4e5b-a44e-611a9b31bf75)

**Comment by stantanasi** [comment]
I don't know which provider you use but it's probably because there is no video source available, so you just can't watch this one

**Comment by DjSpartaKe254** [comment]
Thanks for the effort bro..

**Comment by Farid001979** [comment]
SuperStream

**Comment by Farid001979** [comment]
> I don't know which provider you use but it's probably because there is no video source available, so you just can't watch this one

SuperStream

**Comment by stantanasi** [comment]
**Possibility to change app UI layout on [Release 1.6.4](https://github.com/stantanasi/streamflix/releases/latest)**
